<?php

namespace App\Http\Requests\api;

// use Modules\HR\App\Models\HrAbsentRequests;
 use Illuminate\Foundation\Http\FormRequest;

class ApiDeviceRegRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            "os"=> 'required|in:ios,andr,other',
            "device_id"=> 'required|string',//device UUID
            "FCM_Token"=> 'required|string',//Firebase Cloud Messaging Device Token It is a unique ID generated by Firebase on the mobile device that allows your backend to send push notifications to that specific device.


        ];
    }
}
