<?php

return [
    'permissions' => [
        'debugbar',
        'Debugbar_assets',
        'debugbar_queries',
        'Debugbar_cache',
        'Laravelpwa',
        'Auth',
        'Reset',
        'Password',
        'Lookup',
        'api_vehicles',
        'api_products', 
        'api_API',
        'Subscription',
        'subscriptions',
        'Hr_hr-Attendance',
        'Hr',
        'Hr_termination_types',
        'Hr_terminations',
        'hr_AttendanceMove',
        'Api_operation',
        'Operation',
        'boost',
        'api_basicdata',
        'basicdata_kitchens',
        'basicdata_service_points',
        'store_Ajex',
        'employees',
        'vc',
    ],
];
